### ISSUE TITLE
Store key in services config

### ISSUE THREAD

**Issue by Garbee** [adiachenko/laravel-recaptcha#1]
The recaptcha keys seem to be using a custom config file. It would make more sense to load then out of the default services configuration and let developers override the key if they feel they want something else. That way it follows the convention laravel had where auxiliary services have their keys loaded through that one configuration file.

**Comment by adiachenko** [comment]
@Garbee This is a sound suggestion.

We don't really require separate config file with only 2 credentials, but the env variables should still be customizable.

This is a breaking change though which requires a major version bump. Sorry for the inconvenience that might have caused you. Follow [the upgrade guide](https://github.com/adiachenko/laravel-recaptcha/releases/tag/3.0.0) to update your package to the latest version.

**Comment by Garbee** [comment]
It isn't causing me any problems right now. I just looked through the code and saw it wasn't using the `services` file which is fairly customary with 3rd party API keys at this point. Figured I'd bring it up to get it looked at early before even more people hop on using it. :wink:

Thank you!
